- cmd/netinit/netinit.go
- cmd/sysinit/sysinit.go
- cmd/ttyinit/ttyinit.go
- config/schema.go
- config/types.go
- pkg/network/dhcpcd.go
- pkg/network/network.go
Support both setting DHCP and static address on muti-interfaces
- enp0s3: STATIC mode
- enp0s8: STATIC mode
- enp0s9: DHCP mode
```
k3os:
network:
dns:
nameservers:
- 10.22.0.1
- 8.8.4.4
searches:
- expressvpn
interfaces:
enp0s3:
addresses:
- 10.0.2.20/24
gateway: 10.0.2.2
metric: 180 # if metric not setting, will use default value: 400 + interface_index
enp0s8:
addresses:
- 10.0.3.21/24
gateway: 10.0.3.2
```
```
$ reboot
```
or
```
$ k3os-netinit
```
- Local-Link configuration should be considered
> Optimization of setting network

- overlay/etc/init.d/ccapply
- overlay/etc/init.d/cloud-config
- overlay/etc/init.d/issue
The OpenRC net-online script [provides](https://github.com/OpenRC/openrc/blob/master/init.d/net-online.in#L18) `network-online`, not `net-online` (despite being in a file called `net-online`...).
> Init scripts should wait for the right network-online

- README.md
tar command needs 'z' option to extract gzip archive.
> Add option 'z' to tar in arm installation section

- Dockerfile.dapper
- images/00-base/Dockerfile
- images/01-k3s/Dockerfile
The k3s version has not been bumped in a long time, which is the main motivation for this. But with the recent Go HTTP2 CVEs I wanted to get that in as well. Alpine 3.10 was just a bonus to keep things fresh. I've tested the resulting artifacts in VirtualBox.
> update alpine, golang, and k3s versions

- overlay/etc/inittab
- overlay/etc/securetty
- overlay/libexec/k3os/boot
This moves `/etc/inittab` and `/etc/securetty` static base files out of here-documents in the boot script (they are appended too during boot dynamically based on the tty/ttyS profile). Also renamed the `setup_inittab` function to `setup_ttys` as that is its primary concern.
> overlay: refactor static here-docs in boot script

- pkg/cc/funcs.go
The additional whitespace cause connman main config improper setup.
> Remove extra whitespace in connman config filename

- images/01-k3s/Dockerfile
This updates the k3s install script to match the [install.sh](https://github.com/rancher/k3s/blob/master/install.sh) for the specified k3s version (aka tag).
> update k3s install.sh to match version

- images/01-kernel-stage1/Dockerfile
- images/02-rootfs/Dockerfile
- overlay/libexec/k3os/functions
This bumps the kernel to [`4.15.0-62.69-rancher1`](https://github.com/rancher/k3os-kernel/releases/tag/4.15.0-62.69-rancher1) and incorporates #140 from @kraney
> bump kernel to 4.15.0-62.69-rancher1

- .gitignore
- images/00-base/Dockerfile
- images/01-k3s/Dockerfile
- images/02-rootfs/Dockerfile
- overlay/etc/conf.d/k3s-service
- overlay/etc/conf.d/net-online
- overlay/etc/init.d/ccapply
- overlay/etc/init.d/cloud-config
- overlay/etc/init.d/issue
- overlay/etc/init.d/net-online
- overlay/libexec/k3os/boot
- scripts/run-qemu
Reverts to alpine 3.9 for the base build. This side-steps:
- connman segfaulting after mostly setting up the NIC
- dbus-daemon failing to start
Additionally, this includes:
- removal of the `apk` executable
- forked openrc `net-online` script that actually works
- establishes default runlevel boot order
- (network-online) -> [cloud-config] -> ccapply -> k3s-service
with `network-online` attempted but not preventing bootup of downstream services if it fails and the optional `cloud-config` running before ccapply if present
Fixes #183
Fixes #179
Fixes #88
> base: revert to alpine 3.9

- pkg/config/coerce.go
- pkg/config/read.go
This adds a mapper for cloud-config schemas to coerce a `map[string]interface{}` to `map[string]string`.
Fixes #95
> config: yaml numbers to json strings in maps

- README.md
Removed duplicate reference to k3os.token in phases table.
> Duplicate reference to k3os.token

- overlay/etc/conf.d/wpa_supplicant
- overlay/libexec/k3os/boot
On installations with `k3os.wifi` configuration, this changes lets openrc know to start `wpa_supplicant` prior to `connman`.
> boot: with wifi config, have connman "want" wpa_supplicant

- overlay/libexec/k3os/boot
- overlay/libexec/k3os/mode-disk
This tweaks #189 to work on `/dev/[svx]da` disks.
Also replicated the changes for #189 to work during boot for RPI installs (growpart live!).
/cc @Alxandr
> pre-init: fix growpart logic to handle nvme partitions

- images/02-rootfs/Dockerfile
This addresses #194 by correctly adjusting the ldd and coreutils symlinks.
> rootfs: fix ldd symlink

- package/packer/aws/template-arm64.json
Pull in the ARM64 ISO and not the AMD64.
> package: fix the packer aws template for arm64

- pkg/config/read.go
As outlined in #216 I noticed an issue with spaces in quoted kernel arguments. I found this regex to be a nice way to parse the kernel arguments.
I choose regex because kernel arguments should be fairly bounded & this regex defines a nice lexicon for what is possible in kernel arguments. I am by no means a regex expert so it may be good to add some testing. I didn't see a good pattern for how to adjust the code to make it more testable, but I'm happy to make changes requested!
> fixes #216 - Parse quoted kernel arguments

- pkg/command/command.go
I was running into issues around using `boot_cmd` in a kernel parameter (subsequent PR to follow to fix that). I added this to give me a bit more information during the boot process & thought it might be useful!
> Added logging to commands

- overlay/sbin/k3os-upgrade-kernel
- overlay/sbin/k3os-upgrade-rootfs
mount's options argument takes a comma separated list of options according to the man pages.
/cc @bhale
> Fix mount options in upgrade scripts

- images/06-iso/Dockerfile
- images/06-iso/config.yaml
This demonstrates where to please custom config.yaml into the project tree when there is a need to create a custom ISO image from source.
Addresses #238
> iso: stub out custom config.yaml

- package/packer/openstack/template.json
Small change to sort a few typos and create a variable for Openstack flavors
> FIX: couple of typos ; moving flavor to env variable

- overlay/etc/conf.d/net-online
- pkg/ssh/ssh.go
- scripts/run-qemu
ssh.SetAuthorizedKeys() will now retry up to 10 times, sleeping 1 second in between,
to read public keys from github (if any are specified). This moots the need for the
ping-test in net-online and addresses #224 while maintaining a best-effort attempt to
read github public keys.
`net-online` var `include_ping_test` reverts to a default value of "no"
> ccapply: avoid aggressive fail when reading ssh keys from github

- pkg/cc/funcs.go
If the `k3os.mode` (read from `/var/run/k3os/mode`) is not empty then add node-label `k3os.io/mode=${k3os.mode}`.
This allows for node affinities/anti-affinities dependent on the mode or for scheduling of daemonset pods for the k3os operator only on nodes where this label is present.
> ccapply: add label with the value of k3os.mode

- scripts/run-qemu
With this change, invoking `scripts/run-qemu` with this following arguments will result in the activation of qemu-guest-agent in the guest VM:
- `k3os.mode=live`
- `'boot_cmd="echo GA_PATH=/dev/vport0p1>/etc/conf.d/qemu-guest-agent"'`
Unless the `$STATE_DIR` envvar is overridden, the `qga.sock` will be in the `build/state/k3os-$TAG` directory.
e.g.
`echo '{"execute":"guest-get-osinfo"}' | socat unix-connect:/tmp/qga.sock stdout`
Addresses #291
> scripts/run-qemu: enable host qga socket by default

- images/00-base/Dockerfile
- overlay/etc/ssh/sshd_config
Add default, secure values for `/etc/ssh/sshd_config` via overlay. Importantly, this means that `PasswordAuthentication=no` by default which is a change from previous releases.
Fixes #317
Fixes #262
> sshd_config: establish default values in overlay

- pkg/config/read_cc.go
`source /run/k3os/userdata` instead of direct execution because `/run` is mounted `noexec`.
Fixes #316
> correct execution of userdata when it is a script

- images/00-base/Dockerfile
Skip Alpine 3.10 with the buggy `connmand` that seems fixed in 3.11
> base/rootfs: bump to alpine 3.11

- overlay/etc/sysctl.d/00-k3os.conf
- pkg/cli/rc/rc.go
- pkg/enterchroot/enter.go
- bump rlimit_nofile, rlimit_nproc to defaults from linuxkit
- adapt linuxkit sysctl.d entries
- setup hostname early just like linuxkit
Fixes #342
Fixes #87
> learn from linuxkit

- README.md
for `k3os.ntp_servers` and `k3os.dns_nameservers`
Supersedes #337
> add some emphasis to the fallback nature of config

- go.mod
- go.sum
- pkg/cli/app/app.go
- pkg/cli/install/install.go
- pkg/cli/upgrade/upgrade.go
- pkg/system/component.go
- vendor/github.com/otiai10/copy/.gitignore
- vendor/github.com/otiai10/copy/.travis.yml
- vendor/github.com/otiai10/copy/LICENSE
- vendor/github.com/otiai10/copy/README.md
- vendor/github.com/otiai10/copy/copy.go
- vendor/github.com/otiai10/copy/go.mod
- vendor/github.com/otiai10/copy/go.sum
- vendor/modules.txt
Introducting `k3os upgrade` and hiding `k3os install` when `k3os.mode` == `local`:
```
$ k3os upgrade --help
NAME:
k3os upgrade - perform upgrades
USAGE:
k3os upgrade [command options] [arguments...]
OPTIONS:
--kernel             upgrade the kernel [$K3OS_UPGRADE_KERNEL]
--rootfs             upgrade k3os+k3s [$K3OS_UPGRADE_ROOTFS]
--remount            pre-upgrade remount? [$K3OS_UPGRADE_REMOUNT]
--sync               post-upgrade sync? [$K3OS_UPGRADE_SYNC]
--reboot             post-upgrade reboot? [$K3OS_UPGRADE_REBOOT]
--source value       (default: "/k3os/system") [$K3OS_UPGRADE_SOURCE]
--destination value  (default: "/k3os/system") [$K3OS_UPGRADE_DESTINATION]
```
This enables the future system-upgrade-controller integration, or similar, that run from within the `rancher/k3os` container …
> cli: upgrade sub-command

- images/01-k3s/Dockerfile
- images/02-rootfs/Dockerfile
- overlay/libexec/k3os/boot
- overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml
- package/Dockerfile
- pkg/cc/funcs.go
- pkg/mode/mode.go
See https://github.com/rancher/system-upgrade-controller
also:
- fixes broken ldd with alpine 3.11
- bumps k3s to v1.17.0+k3s.1
> introduce the system-upgrade-controller

- README.md
- images/02-progs/Dockerfile
> update linuxkit/metadata supporting hetzner

- README.md
In the Remastering ISO section of the README.md note that it is not
uncommon for `grub-mkrescue` from grub2 installations to create `boot/grub2`
instead of the expected `boot/grub`.
Addresses #288 (and possibly #358)
> readme: note grub2 differences on non-alpine platforms

- images/00-base/Dockerfile
- overlay/libexec/k3os/boot
udev-settle is added to sysinit if `/etc/conf.d/udev-settle` is present
Fixes #151
> udev-trigger as sysinit service

- install.sh
Kernel partition table is not updated in time for checks, script fails. Brief sleep resolves this.
> partprobe race conditition

- overlay/etc/conf.d/udev-coldplug
- overlay/etc/conf.d/udev-root
- overlay/etc/init.d/udev-coldplug
- overlay/etc/init.d/udev-root
- overlay/libexec/k3os/boot
This address a gap created by `udev-trigger` performing coldplug initialization prior to `hwdrivers` loading modules for detected hardware.
Fixes #426
> init: split udev-trigger into root+coldplug

- images/00-base/Dockerfile
Address #103 by allowing installations to set timezone, e.g. for `America/Phoenix`:
```bash
ln -vs /usr/share/zoneinfo/America/Phoenix /etc/localtime
echo 'America/Phoenix' > /etc/timezone
```
Address an issue caused by Alpine upstream refactoring terminfo
packaging with ncurses.
> base: add tzdata and ncurses-terminfo

- images/10-kernel-stage1/Dockerfile
- images/70-iso/Dockerfile
- images/70-iso/wrapper
- install.sh
- overlay/libexec/k3os/live
At some point I broke the bootability of the ISO image from USB. It seems to be fixed now.
The inclusion of hfsplus/nls modules on the initrd enables the (previously disabled) booting of the embedded hfsplus partition created by grub-mkrescue.
> iso: fix usb image

- overlay/libexec/k3os/boot
- overlay/libexec/k3os/mode-disk
this should hopefully mitigate "resource or mount point busy" on first
boot.
> consistently sleep after partprobe during grow

- images/20-rootfs/Dockerfile
- overlay/libexec/k3os/boot
As discussed in #282.
Should it maybe be synlinked to `/var/libexec/kubernetes`?
Also, I haven't tested this at all.
> Fix /usr/libexec/kubernetes by symlinking to /var/lib/rancher/k3s/agent/libexec/kubernetes

- README.md
Although upgrade scripts are deprecated, assume they are still useful for single node/dev installations.  Updating README to match changes made in #369
> Correct upgrade script locations

- overlay/libexec/k3os/mode
This is likely a common error as it's the first error people encounter when forgetting to set up any cmdline.
> Make "Failed to determine boot mode" a little more user friendly

- overlay/libexec/k3os/mode
I haven't been able to test this, but I believe this would fix #376, #458, and #462. See https://github.com/rancher/k3os/issues/376#issuecomment-641139116
> Wait 30 seconds before failing to determine mode

- images/70-iso/grub.cfg
Added a Grub option for starting the installer so a user does not need to login as `rancher` user and run `sudo k3os install`.
I've tested the Grub option manually with an existing ISO but haven't built my own ISO to verify but it seems low-risk.
This solves https://github.com/rancher/k3os/issues/499
> Added a Grub option for moving straight to install

- overlay/libexec/k3os/mode-disk
Handles case where /sbin is a symlink to /usr/sbin
Current state fails later on `mkdir -p $TARGET/usr/sbin` - it already exists but is a broken symlink.
> Fix takeover on Ubuntu

- pkg/cliinstall/ask.go
> cli: fix typo of "separated" in install

- install.sh
- overlay/libexec/k3os/boot
* pass correct TTY to getty for serial console
* support specifying baud rate as part of console kernel argument
* default baudrate to 9600 to align with kernel default
Fixes #492
> TTY config fixes

- install.sh
If mounting the discovered USB device fails during install, try again mounting the bare device, i.e. /dev/sdb3 -> /dev/sdb.
Fixes #527
> mount from bare usb device if mount fails

- README.md
The example k3os.install.config_url now points to a gist that gives me
ssh access. :imp:
> readme: tweak example config gist url

- install.sh
Simple bounded retry loop in get_url to guard against race conditions with network coming on.
Fixes #386
> install.sh: bounded retry loop get_url

- package/packer/openstack/README.md
- package/packer/openstack/template-arm64.json
- package/packer/openstack/template.json
This commit:
* Simplifies the build templates; OpenStack authentication options are
automatically picked up by Packer and so don't need specifying in the
templates themselves
* Clarifies pre-requisites and includes an example set of steps for
booting the created image
> [OpenStack] Simplify templates, update documentation

- pkg/cc/funcs.go
Fix K3S_URL, K3S_TOKEN, and K3S_CLUSTER_SECRET being passed to k3s
install.sh with extra quotes around the values. Rely on k3s install.sh
to correctly capture entries for `/etc/rancher/k3s/k3s-service.env`.
Fixes #589
> k3s: avoid over-quoting install envvars

- images/00-base/Dockerfile
Previously, wpa_supplicant was install implicitly as a dependency of connman. In alpine 3.12 it is no longer a depedency and needs to be added seperately.
Fixes #593
> Install wpa_supplicant explicitly

- README.md
As stated in this issue: https://github.com/rancher/k3os/issues/556, users need to apply a diff label to enable auto upgrades on v11+.
> New instructions how to enable auto-upgrade V11+

- images/00-base/Dockerfile
irqbalance distributes hardware interrupts across processors. If there is only 1 CPU it will silently exit.
Increases performance in multiprocessor/multicore systems.
Seems to reduce "CPU Stuck" issue with nested virtualization.
> Add irqbalance

- images/10-kernel-stage1/Dockerfile
Add r8152 module to initramfs to enable netboot from r8152 based USB Ethernet adapter.
This PR can be extended to include more USB Ethernet devices if needed.
> feat: Allow netbooting using r8152 based USB Ethernet adapter

- package/packer/aws/template-arm64.json
- package/packer/aws/template.json
Fixes #117 
Currently `us-east-1` is hard coded as a variable, but the official Packer instructions in https://github.com/rancher/k3os/blob/master/package/packer/aws/README.md#setup instruct the user to set AWS_DEFAULT_REGION
> Set AWS Packer region using AWS_DEFAULT_REGION

- pkg/cc/apply.go
Documentation says that sysctls gets applied also on runtime but currently that is not the case so this PR will fix it.
> Apply sysctls also on runtime

- images/05-base/Dockerfile
…in Alpine 3.12 the open-vm-tools package was split into multiple packages. This closes #634
> Add missing open-vm-tools modules

- package/packer/vsphere/server/k3os-server.json
There is a breaking change in packer, storage is now a separate subobject. 
This is the result of running the "fix" within Packer itself that converts the old format to the new format.
> Updated config with packer fix for version 1.6.5

- overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
Fixes problem with system-upgrade-controller and FQDN https://github.com/rancher/system-upgrade-controller/issues/110
> 
> Features and Enhancements
>     Bump wrangler to v0.8
>     Support Env and EnvFrom entries on Plans
> Bug Fixes
>     Fix for incorrect job names for nodes with FQDN
Now as a draft as v0.7.0 is a pre-release
> system-upgrade-controller: bump to v0.7.0

- pkg/enterchroot/enter.go
This avoid a Go bug which crashes some go processes in Containers
The crashes look like:
I0601 05:18:25.815579       1 main.go:288] Listening securely on :9443
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
Discussion at: https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug
ulimit -l is changed from 64 to 65536
> Add code to increase mlocks (ulimit -l)

- overlay/libexec/k3os/mode-disk
We should sync between making a filesystem change and a `poweroff -f`.
> mode-disk: sync before `poweroff -f`

- overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml
The system upgrade controller manifests only specify a toleration for the deprecated  `node-role.kubernetes.io/control-plane=true:NoSchedule` taint. I run my clusters with the newer `node-role.kubernetes.io/control-plane=true:NoSchedule` taint but I have to manually  patch the system-upgrade-controller manifests for it to run with the newer control-plane taint. 
* Add `node-role.kubernetes.io/control-plane` toleration to  system-upgrade-controller manifests.
* Bump system-upgrade-controller to v0.7.5.
Tested manifest changes in k3os kubernetes clusters -- system-upgrade-controller runs correctly in clusters with `node-role.kubernetes.io/control-plane=true:NoSchedule` taint on controller nodes. Also tested v0.7.5 deploys and starts up correctly.
> Add control-plane toleration to system-upgrade-controller.

- overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rancher/system-upgrade-controller:v0.7.7-rc.1
- rancher/kubectl:v1.21.5
(cherry picked from commit d567c424b0511a9805f66719942db2f24596afd8)
> upgrade: suv v0.7.7-rc.1

- images/00-base/Dockerfile
Enables running (some) binaries compiled against glibc.
> base: add libc6-compat and gcompat

- images/00-base/Dockerfile
Enables running (some) binaries compiled against glibc.
(cherry picked from commit 892e3168962cd8b3b7fc40e0dab7195e084545c3)
> [backport v0.21.x] base: add libc6-compat and gcompat

- images/00-base/Dockerfile
Enables running (some) binaries compiled against glibc.
(cherry picked from commit 892e3168962cd8b3b7fc40e0dab7195e084545c3)
> [backport v0.20.x] base: add libc6-compat and gcompat

- images/00-base/Dockerfile
Enables running (some) binaries compiled against glibc.
(cherry picked from commit 892e3168962cd8b3b7fc40e0dab7195e084545c3)
> [backport v0.19.x] base: add libc6-compat and gcompat

- install.sh
When using force EFI install, install.sh gets set GRUB_TARGET only for x86_64.
> [FEATURE]: Support EFI for arm64

- overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rancher/system-upgrade-controller:v0.8.0
- adjust the manifest to prefer scheduling to master/control-plane
instead of requiring it.
> suc: v0.8.0

- images/10-k3s/Dockerfile
> [release v0.21.x] k3s: v1.21.5+k3s2

- install.sh
We found that when writing the ISO to a usb device, sometimes the `ISO_DEVICE` detection does not find the proper partition as seen below -- notice that the `K3OS` label is at both the entire disk level as well as the individual (correct) partition, yet `blkid` returns `/dev/sd2` (incorrect):
```
barney [~]# fdisk -l /dev/sdk
GPT PMBR size mismatch (19735811 != 61472767) will be corrected by write.
The backup GPT table is not on the end of the device.
Disk /dev/sdk: 29.31 GiB, 31474057216 bytes, 61472768 sectors
Disk model: DataTraveler 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 457E92A0-ECFC-4B72-B7CE-38B7AAA67341
Device        Start      End …
```
> Allow explicit set of ISO_DEVICE env variable
