cmd/control/sysinit.go, config/types.go, pkg/command/command.go
```
#cloud-config
runcmd:
- [ touch, /home/rancher/test1 ]
- echo "test" > /home/rancher/test2
```
=> Add runcmd settings

cmd/netinit/netinit.go, cmd/sysinit/sysinit.go, config/schema.go, config/types.go, pkg/environment/environment.go, pkg/network/proxy.go
If environment key contain "K3S/k3s" it will create `/etc/profile.d/k3s.sh` others will create `/etc/profile.d/k3os.sh`
```
k3os:
environment:
K3S_URL: https://server-url:6443
TEST_ENV: test
```
=> Add environment directive

README.md
Small PR to improve the readability of the README. Looks like it had to be done in a hurry. :)
=> Fix typos, syntax and improve readability

README.md
remove extra power_off from automatic installation
=> remove extra power_off

README.md
move data_source in config.yaml under k3os section
=> update data_source in config.yaml

README.md
* Fixed a few instances where plurals where used instead of singulars, and vice-versa
* Fixed verb tense
=> Minor text fixes in README.md

README.md
=> Docs : fix path inside ISO

README.md
I’ve fixed a couple of typos in README.md. All minor things like missing words or missing backticks.
Keep up the great work!
=> Minor README Fixes

README.md
Addresses rancher/k3os#160. This works on both Xenial and Bionic systems. Additionally, calls out via comment required packages.
=> readme: tweak "Remastering ISO" section

pkg/cc/funcs.go
This will fix ntp not working.
#137 should also be merged as this won't work otherwise.
=> Add [General] to connman's main.conf file

README.md, install.sh, package/packer/aws/template-arm64.json, package/packer/aws/template.json, package/packer/vagrant/vagrant.json
This also updates packer templates to use the latest release.
=> readme: update urls to use v0.3.0

images/01-k3s/Dockerfile, images/06-iso/run-kvm.sh, scripts/run-qemu
Bump the k3s version to recently-ish released v0.9.1.
=> k3s: v0.9.1

images/01-kernel-stage1/Dockerfile
Addresses #220 via rancher/k3os-kernel#8
=> kernel: 4.15.0-65.74-rancher1

install.sh
Don't know if there's a better way to do this?
Fixes #207.
=> Create /opt if it doesn't exist

images/00-base/Dockerfile, images/02-progs/Dockerfile, images/02-rootfs/Dockerfile
=> tooling: add kubectx and kubens v0.7.0

overlay/sbin/k3os-upgrade-kernel
This is to handle the case when the system was installed using the ARM overlay method.
/cc @bhale
=> Don't try to upgrade the kernel if the system is using a custom kernel

install.sh
Fixes the fix for #207 /cc @zimme
=> rootfs: fix /opt

images/01-k3s/Dockerfile
Tested on VirtualBox as server node. 
Making WIP until https://github.com/rancher/k3s/pull/946 is done.
=> latest k3s 0.10.1

README.md, images/06-iso/run-kvm.sh, scripts/run-qemu
- modified README
- modified Qemu scripts
Fixes #254
=> Bump up minimum memory: live=2GB, local 1GB

images/00-base/Dockerfile
=> base: install mdadm

images/01-k3s/Dockerfile
=> k3s: v0.10.2

scripts/run-qemu
- live cd boot
`./scripts/run-qemu k3os.mode=live`
- silent install
`DISK_NAME=test.img ./scripts/run-qemu k3os.password=rancher k3os.mode=install k3os.install.silent k3os.install.device=/dev/vda`
- run installed vm
`DISK_NAME=test.img ./scripts/run-qemu k3os.password=rancher`
- recover installed vm
`DISK_NAME=test.img ./scripts/run-qemu k3os.password=rancher k3os.mode=live`
=> scripts: update run-qemu with some examples

images/01-kernel-stage1/Dockerfile
=> kernel: 4.15.0-70.79

images/01-k3s/Dockerfile
=>  k3s: v1.0.0

overlay/libexec/k3os/mode-local
=> persist /etc/rancher/node across reboots

images/00-base/Dockerfile, overlay/libexec/k3os/boot, overlay/sbin/toolbox
Includes:
- rng-tools by @zimme #270
- htop by @zimme #269
- toolbox by @bhale #257
Fixes #291
Fixes #265
Fixes #256
=> tooling: toolbox, rng-tools, htop, qemu-guest-agent

cmd/rc.init/main.go, go.sum, images/01-gobuild/Dockerfile, images/02-progs/Dockerfile, images/02-rootfs/Dockerfile
instead of building from (forked) source
Prep for #202 
Prep for #294
=> refactor how we build linuxkit bits

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> project: add bug report and feature request templates

images/01-kernel-stage1/Dockerfile
=> kernel: 4.15.0-72.81

images/01-kernel-stage1/Dockerfile
=> kernel: 5.0.0-36.39

install.sh
Bumping version presented via text to end user to the latest k3os version available
=> Updating install.sh message

images/02-rootfs/Dockerfile
- to /etc/ssl/certs/ca-certificates.crt
Fixes #344
=> establish /etc/ssl/cert.pem symlink

images/01-kernel-stage1/Dockerfile
- fixes a packaging issue causing extra modules to go awol
=> kernel: 5.0.0-37.40-rancher2

install.sh
=> Add support for tftp:// and ftp:// config_url and iso_url.

images/00-base/Dockerfile
=> storage tooling: add iscsi, lvm2, and multipath-tools

images/01-k3s/Dockerfile
=> k3s: v1.17.2+k3s1

images/00-base/Dockerfile, overlay/libexec/k3os/boot
=> udev support

images/07-iso/wrapper
=> add joliet info to iso

images/01-kernel-stage1/Dockerfile
=> kernel: 5.0.0-41.45-rancher1

overlay/libexec/k3os/boot
=> init: fix broken killprocs link

package/packer/vagrant/vagrant.json
checksum changed to match 'v0.9.0-rc4'
=> correct checksum

images/07-iso/wrapper, overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
=> bump system-upgrade-controller to v0.4.0

pkg/system/component.go
This allows for upgrade to a version that is already present on the
system by moving it to `${DIR}.old` before replacing it. Subsequent
attempts to upgrade to the version represented by `${DIR}` will fail
until `${DIR}.old` is removed.
Fixes #415
=> upgrade: move existing destination path

README.md
- updated line for ubuntu packages to include grub-pc-bin
- added line for centos packages
- added line for alpine packages
=> update remastering iso pre-reqs in readme

README.md
- replaced with /etc/local.d/example.start
- updated download URLs to v0.10.0
- fix explanation and examples for k3s args
Fixes #430
=> nix /etc/rc.local write_files example

package/packer/openstack/template-arm64.json, package/packer/openstack/template.json
Bumping version in packer templates to latest version of k3os.
=> bump version to 10 w/in packer template

images/00-base/Dockerfile
=> Wireguard Tools

pkg/config/read_test.go
The arrays should not be additive.
=> config: add small test to assert authorized keys

images/10-k3s/Dockerfile
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1176
=> k3s: v1.17.7+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.18.4+k3s1

install.sh
Use the same bootloading strategie than "Current".
Fixes #516
=> Fix Rescue Shell

images/10-kernel-stage1/Dockerfile
=> kernel: 5.4.0-37.41

pkg/ssh/ssh.go
This will allow the following.
```
k3os:
ssh_authorized_keys:
- github:zimme
- gitlab:zimme
- https://fridlund.dev/authorized_keys
- http://fridlund.dev/ssh.keys
```
=> Add support for gitlab as well as urls for ssh_authorized_keys

pkg/cc/funcs.go
This will remove unnecessary AutoConnect and Favorite options as well as setup PreferredTechnologies to prefer ethernet over wifi if both are present.
=> Update networking setup

install.sh
Also add rescue options for both previous and current.
=> install: fix previous menuentry

package/packer/openstack/template-arm64.json, package/packer/openstack/template.json
Update packer templates to reference 10.3
=> updating openstack packer template to 10.3

images/10-k3s/Dockerfile, overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml, overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml
- k3s v1.18.6+k3s1
- suc v0.6.2
=> bump k3s and suc

install.sh
=> fix dueling gettys

overlay/libexec/k3os/boot
=> create /var/lib/nfs in boot

images/00-base/Dockerfile
Pretty self-explanatory
Fixes #461
=> Upgrade k3os-base image to use Alpine 3.12

images/10-k3s/Dockerfile
=> k3s: v1.19.2+k3s1

package/packer/hetzner/README.md, package/packer/hetzner/config.yaml, package/packer/hetzner/template.json
Made a packer config for build k3OS on Hetzner Cloud
Could be useful for someone
Cloud-init working fine, also tested with Hetzner Cloud terraform provider
=> Add packer config for Hetzner Cloud

README.md
README updates:
* Fixed some typos and consistency in spacing and formatting.
* Fixed some warnings reported by the Markdown linter (https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md).
=> Fixed some typos in the README.

images/10-kernel-stage1/Dockerfile
=> kernel: 5.4.0-70.78-rancher1

images/10-k3s/Dockerfile
=> k3s: v1.19.8+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.20.4+k3s1

overlay/etc/motd
Not a native speaker myself, but I think it should be like this.
Signed-off-by: Michael Vetter <jubalh@iodoru.org>
=> Improve motd text

images/00-base/Dockerfile
=> add package smartmontools

Dockerfile.dapper, go.mod, images/10-gobuild/Dockerfile, images/20-progs/Dockerfile, scripts/run-qemu
=> golang: 1.16.x

package/packer/proxmox/config/cloud.yml, package/packer/proxmox/template.json, package/packer/proxmox/vars.json
Fixes: https://github.com/rancher/k3os/issues/602
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
=> packer/proxmox: adjust to v0.20.4

package/packer/vagrant/README.md, package/packer/vagrant/template.json, package/packer/vagrant/template.pkr.hcl
=> update packer scripts and manual for virtualbox

images/10-kernel-stage1/Dockerfile
=> kernel: 5.4.0-72.80-rancher1

images/10-k3s/Dockerfile
=> k3s: v1.19.10+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.20.6+k3s1

images/10-kernel-stage1/Dockerfile, images/70-iso/grub.cfg, install.sh, scripts/run-qemu
- leave apparmor disabled by default
Addresses #702 
=> kernel: 5.4.0-73.82-rancher2

images/10-k3s/Dockerfile
=> k3s: v1.19.11+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.20.7+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.21.1+k3s1

.drone.yml, scripts/images
=> drone: rancher/dapper:v0.5.0

images/10-kernel-stage1/Dockerfile
=> kernel: 5.4.0-84.94-rancher1

images/10-kernel-stage1/Dockerfile
(cherry picked from commit 4d28d439164f106b3aa9d5beb80e779cf7fdc848)
=> [backport v0.19.x] kernel: 5.4.0-84.94-rancher1

images/10-kernel-stage1/Dockerfile
(cherry picked from commit 4d28d439164f106b3aa9d5beb80e779cf7fdc848)
=> [backport v0.20.x] kernel: 5.4.0-84.94-rancher1

images/10-k3s/Dockerfile
=> k3s: v1.19.15+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.20.11+k3s1

Dockerfile.dapper, images/00-base/Dockerfile, images/10-gobuild/Dockerfile
=> base: bump alpine:3.14

images/10-k3s/Dockerfile
=> k3s: v1.21.5+k3s1

overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rancher/system-upgrade-controller:v0.7.7-rc.1
- rancher/kubectl:v1.21.5
=> upgrade: suv v0.7.7-rc.1

overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rancher/system-upgrade-controller:v0.7.7-rc.1
- rancher/kubectl:v1.20.11
(cherry picked from commit 50980c182be7e1dbcd856411d3147178bd9b0bf0)
=> upgrade: suc v0.7.7-rc.1 (#761)

overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rancher/system-upgrade-controller:v0.7.7-rc.1
- rancher/kubectl:v1.19.15
(cherry picked from commit 50980c182be7e1dbcd856411d3147178bd9b0bf0)
=> [backport v0.19.x] upgrade: suc v0.7.7-rc.1 (#761)

images/05-base/Dockerfile
add sub package open-vm-tools for 1.21
v0.21.0-k3s1r0 does not content this fix
=> fix vsphere vmwaretools 1.21

images/10-k3s/Dockerfile
=> k3s: v1.22.2+k3s1

images/10-k3s/Dockerfile
=> k3s: v1.22.2+k3s2

images/10-k3s/Dockerfile
=> [release v0.20.x] k3s: v1.20.11+k3s2

images/10-k3s/Dockerfile
=> [release v0.19.x] k3s: v1.19.15+k3s2

README.md
Added note pointing users to elemental and asking not to use this project anymore.
=> update readme to include deprecation notice
